version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy-alpine:latest
    volumes:
      - ./front_envoy/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8080:80"
      - "9901:9901"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'front-envoy' --service-node 'front-envoy' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  hello_envoy:
    image: envoyproxy/envoy-alpine:latest
    volumes:
      - ./hello/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8786:8786"
      - "8788:8788"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'hello' --service-node 'hello' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  hello:
    build: hello/
    ports:
    - "8081:8081"

  hi_envoy:
    image: envoyproxy/envoy-alpine:latest
    volumes:
      - ./hi/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8789:8789"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'hi' --service-node 'hi' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  

  hi:
    build: hi/
    ports:
    - "8082:8082"

  ola_envoy:
    image: envoyproxy/envoy-alpine:latest
    volumes:
      - ./ola/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8790:8790"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'ola' --service-node 'ola' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  

  ola:
    build: ola/
    ports:
    - "8083:8083" 