static_resources:
  listeners:
  - name: "hello-svc-http-listener"
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8786
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: hello_host
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: hello_cluster
          http_filters:
          - name: envoy.router
            typed_config: {}
  - name: "hi-svc-http-listener"
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8788
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: egress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: hi_host
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: hi_cluster
          http_filters:
          - name: envoy.router
            typed_config: {}
  - name: "ola-svc-http-listener"
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8790
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: egress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: ola_host
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: ola_cluster
          http_filters:
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: hello_cluster
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: hello_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: hello_service
                port_value: 8081
  - name: hi_cluster
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: hi_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: hi_envoy
                port_value: 8789
  - name: ola_cluster
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: ola_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: ola_envoy
                port_value: 8790
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
